spring:
  application:
    name: localhost
server:
  port: 10086
eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/