server:
  port: 10069
spring:
  application:
    name: xiaoliu-zuul
eureka:
  instance:
    hostname: xiaoliu-zuuls
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
#      实现了负载均衡
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: xiaoliu-feign
    api-b:
      path: /api-b/**
      serviceId: xiaoliu-ribbon

